apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: frontend
spec:
  type: NodePort  # Exposición del servicio a través de un nodo del clúster
  ports:
    - port: 80         # Puerto interno del servicio
      targetPort: 80    # El contenedor escucha en el puerto 80 (Nginx, por ejemplo)
      nodePort: 30080   # Puerto expuesto desde fuera del clúster
  selector:
    app: microservice  # Coincide con los labels del Deployment/Pod
